name: Compile

on: push

jobs:
  build:
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          # - os: ubuntu-latest
          #   compiler: gcc
          # - os: ubuntu-latest
          #   compiler: clang
          # - os: windows-latest
          #   compiler: msvc
          # - os: windows-latest
          #   compiler: mingw
          - os: macos-latest
            compiler: clang

        step:
          - name: "Checkout Repository"
            uses: actions/checkout@v4
            with:
              submodules: recursive

          - name: "Setup required packages"
            run: |
              brew install cmake ninja mesa-glu mesa xorg-server

          - name: "Setup cmake"
            run: |
              cmake -B build -DCMAKE_BUILD_TYPE=Debug
              cmake --build build
